version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: looptable_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - backend/.env

volumes:
  db-data:
    name: looptable-db-data
